config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :projects do
    resources :collaborators, only: [:new, :create, :show, :destroy]
    resources :tasks
    resources :notes
  end
  resources :users, only: [:index, :new, :create]
  get '/projects/filter/:q' => 'projects#filter', as: 'project_filter'
  get '/login' => 'sessions#new'
  get '/signup' => 'users#new'
  post '/login' =>'sessions#create'
  delete '/logout' => 'sessions#destroy'


  get '*path', to: 'application#bad_route_redirect'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :get_note, only: [:edit, :update, :destroy]
  before_action :find_project

  def index
    @notes = current_user.user_notes.flatten
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(content: params[:note][:content], project_id: params[:project_id], user_id: current_user.id)
    current_user.notes << @note
    if @note.valid?
      @note.save
      current_user.user_notes << @note

      redirect_to project_path(@note.project)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @note.update!(content: params[:note][:content],
      project_id: params[:project_id], user_id: current_user.id)
      redirect_to project_path(@project.id)
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to project_path(@project.id)
  end

  private

    def get_note
      @note = Note.find(params[:id])
    end

    def find_project
      @project = Project.find(params[:project_id])
    end

    def note_params
      params.require(:note).permit(:content, :project_id, :user_id)
    end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_notes_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Note</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
</head>
<body class="note-new-body">
  <section id="sideMenu">
    <h2>WePlan</h2>
    <nav>
      <a href="/users"><i class="fas fa-home"></i>Home</a>
      <a href="/projects"><i class="fas fa-paperclip"></i></i>Projects</a>
    </nav>
  </section>
  <header>
    <div class="search-area">
      <i class="fas fa-search"></i>
    <input type="text" name="" value="">
    </div>
    <div class="user-area">
      <%= link_to "Logout", "/logout", method: "DELETE"%>
      <a href="/root">Home</a>
    </div>
  </header>

   <div class="form-box">
    <h1><%= title_text %></h1>
    <div class="form-inner">
      <%= form_for [@project, @note] do |f|%>
        <%=f.label :content%>
        <%=f.text_area :content%>
        <%=f.submit submit_text%>
      <% end %>
    </div>
  </div>

  
</body>
</html>

app/views/notes/edit.html.erb
<%= render partial: "notes_form", locals: { title_text: "Update Note", submit_text: "Update"}%>
<br>
 

app/views/notes/index.html.erb
<h1><%= current_user.name.capitalize%>'s Notes</h1>
<h2>These are all of your notes:</h2>
<ul>
<% if !@notes.empty? %>
  <% names = []%>
    <% @notes.each do |note| %>
      <% if !names.include?(note.project.name)%>
        <h3>For <%= note.project.name %>:</h3>
        <% names << note.project.name %>
      <% end %>
        <ul>
          <li>"<%=note.content%>"</li>
          <ul>
            <li><%= link_to "Edit Note", edit_project_note_path(@project.id, note.id)%></li>
          </ul>
        </ul>
    <% end %>
  <% end %>
</ul><br>

<%= link_to "Add a Note", new_project_note_path(@project.id) %><br>

<br>
<br>
<%= link_to "Home", users_path%>     <%= link_to "Return to Project Page", projects_path %>
 <%= link_to "Logout", "/logout", method: "DELETE"%>

app/views/notes/new.html.erb
<%=render partial: "notes_form", locals: {title_text: "Create Note", submit_text: "Add Note"}%>