config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :projects do
    resources :collaborators, only: [:new, :create, :show, :destroy]
    resources :tasks
    resources :notes
  end
  resources :users, only: [:index, :new, :create]
  get '/projects/filter/:q' => 'projects#filter', as: 'project_filter'
  get '/login' => 'sessions#new'
  get '/signup' => 'users#new'
  post '/login' =>'sessions#create'
  delete '/logout' => 'sessions#destroy'


  get '*path', to: 'application#bad_route_redirect'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def format_due_date
    self.due_date.strftime("%A, %B %d, %Y")
  end

  def capitalize_stuff
    self.name.split.map{|x| x.capitalize}.join(" ")
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_task, only: [:show, :edit, :update, :destroy]
  before_action :find_project

  def index
    @tasks = current_user.user_tasks.flatten
  end

  def new
    @task = Task.new
  end

  def create
    date = params[:task][:"due_date(3i)"]+"/"+params[:task][:"due_date(2i)"]+"/"+ params[:task][:"due_date(1i)"]
    @task = Task.new(name: params[:task][:name],
      description: params[:task][:description], due_date: date,
      status: params[:task][:status], project_id: params[:project_id])
    if @task.valid?
      @task.save
      current_user.user_tasks << @task
      redirect_to project_path(@project.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    date = params[:task][:"due_date(3i)"]+"/"+params[:task][:"due_date(2i)"]+"/"+ params[:task][:"due_date(1i)"]
    if @task.update!(name: params[:task][:name],
      description: params[:task][:description], due_date: date,
      status: params[:task][:status], project_id: params[:project_id])
      redirect_to project_path(@project.id)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_path(@project.id)
  end

  private
    def get_task
      @task = Task.find(params[:id])
    end

    def find_project
      @project = Project.find(params[:project_id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :due_date, :status, :project_id)
    end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_tasks_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Task</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
</head>
<body class="task-form-body">
  <section id="sideMenu">
    <h2>WePlan</h2>
    <nav>
      <a href="/projects"><i class="fas fa-paperclip"></i>All Projects</a>
      <a href="<%= project_path(@project.id)%>"><i class="fas fa-paperclip"></i>Return to Project</a>
    </nav>
  </section>

  <header>
    <div class="search-area">
      <i class="fas fa-search"></i>
    <input type="text" name="" value="">
    </div>
    <div class="user-area">
      <%= link_to "Logout", "/logout", method: "DELETE"%>
      <a href="/root">Home</a>
    </div>
  </header>

  
<div class="form-box">
<h1><%= title_text %></h1>
  <div class="form-inner">
    <%= form_for [@project, @task] do |f|%>
      <% if @task.errors.any? %>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <% end %>
      <%=f.label :name%>
      <%=f.text_field :name%>
      <%=f.label :description%>
      <%=f.text_area :description%>
      <%=f.label :due_date%>
      <%=f.date_select :due_date, {order: [:month, :day, :year],
        prompt: { day: 'Select day', month: 'Select month', year: 'Select year'},
        start_year: Date.today.year - 20, end_year: Date.today.year + 100}, {required: true}%>
      <%=f.label :status%>
      <%=f.select :status, options_for_select(["Not Started", "In Progress", "Complete"]) %>
      <%=f.submit submit_text %>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/tasks/edit.html.erb
<%= render partial: "tasks_form", locals: { title_text: "Update Task", submit_text: "Update Task"}%>



 

app/views/tasks/index.html.erb
<h1>Hello <%=current_user.capitalize_stuff %>!</h1>
<h2>These are all of your tasks for <%= @project.capitalize_stuff %>:</h2>
<ul>
  <% if !@tasks.empty? %>
  <% names = []%>
    <% @tasks.each do |task| %>
      <% if !names.include?(task.project.name)%>
        <h3>For <%= task.project.capitalize_stuff %>:</h3>
        <% names << task.project.name %>
      <% end %>
        <ul>
          <li><%=link_to task.capitalize_stuff, project_task_path(task.project.id, task.id)%></li>
        <ul>
          <li><%= link_to "Edit Task", edit_project_task_path(task.project.id, task.id)%></li>
        </ul>
      </ul>
    <% end %>
  <% end %>
</ul><br>

<br>
<br>
<%= link_to "Home", users_path%>  <%= link_to "Return to Project Page", projects_path %>
<%= link_to "Logout", "/logout", method: "DELETE"%>

app/views/tasks/new.html.erb
<%= render partial: "tasks_form", locals: {title_text: "Create Task", submit_text: "Create Task"}%>

app/views/tasks/show.html.erb
<div class="title">
<h1><%=@task.capitalize_stuff%> Details</h1>
</div><br>

<div class="description">
  <h2>Description:</h2>
  <p><%= @task.description %></p><br>
  <h3>For project: </h3>
  <p><%= link_to @task.project.capitalize_stuff, project_path(@task.project) %></p>
</div><br>

<div class="headers">
  <li>Status: <%=@task.status%></li>
  <li>Due Date: <%=@task.format_due_date%></li>
</div>
<br>
<li><%= link_to "Edit Task", edit_project_task_path(@project.id, @task.id)%></li>

<br>
<%= link_to "Home", users_path%>     <%= link_to "Return to Project Page", projects_path %>
 <%= link_to "Logout", "/logout", method: "DELETE"%>