config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :projects do
    resources :collaborators, only: [:new, :create, :show, :destroy]
    resources :tasks
    resources :notes
  end
  resources :users, only: [:index, :new, :create]
  get '/projects/filter/:q' => 'projects#filter', as: 'project_filter'
  get '/login' => 'sessions#new'
  get '/signup' => 'users#new'
  post '/login' =>'sessions#create'
  delete '/logout' => 'sessions#destroy'


  get '*path', to: 'application#bad_route_redirect'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :collaborators
  has_many :projects, through: :collaborators
  has_many :notes

  validates :name, presence: true
  validates :username, presence:true, uniqueness: true
  validates :email, presence:true, uniqueness: true
  validates :password, presence:true


   def user_projects
     self.projects
   end

   def projects_not_started_count
     user_projects.select {|p| p.status == "Not Started"}.count
   end

   def projects_in_progress_count
     user_projects.select {|p| p.status == "In Progress"}.count
   end

   def completed_projects_count
     user_projects.select {|p| p.status == "Complete"}.count
   end

   def user_project_names
     user_projects.collect {|project| project.name}
   end

   def user_tasks
     user_projects.collect {|project| project.tasks}
   end

   def user_task_names
     user_tasks.collect {|task| task.name}
   end

   def user_notes
     user_projects.collect {|project| project.notes}
   end

   def capitalize_stuff
     self.name.split.map{|x| x.capitalize}.join(" ")
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      redirect_to users_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Projects</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
  
</head>

<body class="dashboard-body">
  <section id="sideMenu">
    <h2>WePlan</h2>
    <nav>
      <a href="/users" class="active"><i class="fas fa-home"></i>Home</a>
      <a href="/projects"><i class="fas fa-paperclip"></i></i>Projects</a>
      <a href="/projects/new"><i class="fas fa-sticky-note"></i>Create a Project</a>
    </nav>
  </section>

  <header>
    <div class="search-area">
      <i class="fas fa-search"></i>
    <input type="text" name="" value="">
    </div>
    <div class="user-area">
      <%= link_to "Logout", "/logout", method: "DELETE"%>
      <a href="/root">Home</a>
    </div>
  </header>

  <section id="content-area">
    <div class="greeting-row">
       <div class="greeting">
        <h1>Hello <%= current_user.name.capitalize%>!</h1>
        <h2>Welcome to your Project Planner</h2>
      </div>
      <div class="time-box">
        <h3><%= Time.now.strftime("%A, %B %d, %Y") %></h3>
      </div>
    </div>
  </section>

  <div class="project-status-list">
    <div class="project-status-box not-started status-inner">
    <h4 class="project-title"><%=link_to "Not Started", project_filter_path("Not Started") %></h4>
      <div class="status-content">
        <p>You have <%=current_user.projects_not_started_count %> project(s) that have not been started.</p>
      </div>
    </div>
    <div class="project-status-box in-progress status-inner" >
    <h4 class="project-title in-progress"><%=link_to "In Progress", project_filter_path("In Progress") %></h4>
      <div class="status-content">
        <p>You have <%=current_user.projects_in_progress_count %> project(s) that are in progress.</p>
      </div>
    </div>
    <div class="project-status-box complete status-inner">
     <h4 class="project-title"><%=link_to "Completed", project_filter_path("Completed") %></h4>
       <div class="status-content">
        <p>You have <%=current_user.completed_projects_count %> completed project(s).</p>
      </div>
    </div>
  </div>


</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
  <title>Sign Up</title>
</head>

<body class="sign-up">

  <nav class="navigation-bar">
    <a href="/" class="logo">WePlan</a>
    <ul class="nav-links">
        <li><a href="/login" class="nav-link">Login</a></li>
        <li><a href="/" class="nav-link">Home</a></li>
    </ul>
  </nav>
  <div class="error"> <%= flash.notice %></div>

  <div class="signup-header">
   <h1>Sign Up</h1>
  </div>
  
  <div class="grey-bg">
  
    <div class="space">
    </div>

    <div class="signup-box">
      <div class="form-box">
        <div class="form-inner">
          <%= form_for(@user) do |f| %>
          <% if @user.errors.any? %>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          <% end %>
            <%= f.label :name %>
            <%= f.text_field :name %>
            <%= f.label :email%>
            <%= f.text_field :email%>
            <%= f.label :username %>
            <%= f.text_field :username %>
            <%= f.label :password %>
            <%= f.password_field :password %>
            <%= f.submit 'Sign Up' %>
          <% end %>
        </div>
      </div>
      <div class="signup-reasons-box">
        <h2>Easy</h2>
        <div class="signup-reasons-content">
          <p><i class="fas fa-angle-double-right"></i><span>Get started in minutes. Import existing projects or use a pre-built template to get up and running.<span></p>
        </div>
        <h2>Collaborative</h2>
        <div class="signup-reasons-content">
          <p><i class="fas fa-angle-double-right"></i><span>Share your work in real-time. Access tasks, calendars, files, and discussions from any device, wherever you are.<span></p>
        </div>
        <h2>Flexible</h2>
        <div class="signup-reasons-content">
          <p><i class="fas fa-angle-double-right"></i><span>Manage projects of any size with interactive Gantt charts, resource management, automated workflows, file sharing, and more.<span></p>
        </div>
        <h2>Demonstration</h2>
        <div class="signup-reasons-content">
          <p><i class="fas fa-angle-double-right"></i><span>We’ll walk you through all the project management features that will help you use WePlan to its fullest potential.<span></p>
        </div>
      </div>
    </div>
  </div>



</body>
</html>