config/routes.rb
Rails.application.routes.draw do

  root 'application#index'

  resources :projects do
    resources :collaborators, only: [:new, :create, :show, :destroy]
    resources :tasks
    resources :notes
  end
  resources :users, only: [:index, :new, :create]
  get '/projects/filter/:q' => 'projects#filter', as: 'project_filter'
  get '/login' => 'sessions#new'
  get '/signup' => 'users#new'
  post '/login' =>'sessions#create'
  delete '/logout' => 'sessions#destroy'


  get '*path', to: 'application#bad_route_redirect'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_many :collaborators
  has_many :users, through: :collaborators
  has_many :notes

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :status, presence: true
  validates :due_date, presence: true

  def format_due_date
    self.due_date.strftime("%A, %B %d, %Y")
  end

  def capitalize_stuff
    self.name.split.map{|x| x.capitalize}.join(" ")
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :get_project, only: [:show, :edit, :update, :destroy, :get_project_id]

  def index
    @projects = User.find_by(id: session[:user_id]).projects
  end

  def filter
    @projects = Project.where(:status => params[:q]).select {|p| p.users.include?(current_user)}
    render :index
  end

 def new
    @project = Project.new
 end

  def create
    @project = Project.new(project_params)
    if @project.valid?
      @project.save
      current_user.projects << @project
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update!(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def get_project_id
    @project.id
  end

  private
    def get_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :due_date, :status)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_projects_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
  
  <title>New</title>
</head>
<body class="project-new-body">
  <section id="sideMenu">
    <h2>WePlan</h2>
    <nav>
      <a href="/users"><i class="fas fa-home"></i>Home</a>
      <a href="/projects"><i class="fas fa-paperclip"></i></i>Projects</a>
    </nav>
  </section>

  <header>
    <div class="search-area">
      <i class="fas fa-search"></i>
    <input type="text" name="" value="">
    </div>
    <div class="user-area">
      <%= link_to "Logout", "/logout", method: "DELETE"%>
      <a href="/root">Home</a>
    </div>
  </header>
  
  <div class="form-box">
    <h1><%= title_text %></h1>
    <div class="form-inner">
      <%= form_for @project do |f|%>
        <% if @project.errors.any? %>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        <% end %>
        <%=f.label :name%>
        <%=f.text_field :name%><br>
        <%=f.label :description%>
        <%=f.text_area :description%><br>
        <%=f.label :due_date%>
        <div class="date-format">
          <%=f.date_select :due_date, {order: [:month, :day, :year],
            prompt: { day: 'Select day', month: 'Select month', year: 'Select year'},
            start_year: Date.today.year - 20, end_year: Date.today.year + 100}, {required: true} 
          %>
        </div>
        <%=f.label :status%>
        <%=f.select :status, options_for_select(["Not Started", "In Progress", "Complete"]), {prompt: 'Select Status'} %><br>
        <%=f.submit submit_text %>
      <% end %>
    </div>
  </div>
</body>
</html>
   

app/views/projects/edit.html.erb
<%= render partial: "projects_form", locals: { title_text: "Update Project", submit_text: "Update Project"}%>
<%=form_tag @project, method: "DELETE" do %>
  <%=submit_tag "Delete this Project" %>
<% end %>

app/views/projects/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
  <title>Welcome</title>
</head>
<body class="project-index-body">
  <section id="sideMenu">
    <h2>WePlan</h2>
    <nav>
      <a href="/users"><i class="fas fa-home"></i>Home</a>
      <a href="/projects" class="active"><i class="fas fa-paperclip"></i></i>Projects</a>
      <a href="/projects/new"><i class="fas fa-sticky-note"></i>Create a Project</a>
    </nav>
  </section>

  <header>
    <div class="search-area">
      <i class="fas fa-search"></i>
    <input type="text" name="" value="">
    </div>
    <div class="user-area">
      <%= link_to "Logout", "/logout", method: "DELETE"%>
      <a href="/root">Home</a>
    </div>
  </header>

  <h1 class="project-heading"><%= current_user.capitalize_stuff%>'s Projects</h1>
  <p><%= link_to "Create New Project", new_project_path %></p>

    <div class="user-project-list">
     <h2>Current Projects:</h2>
     <% if !@projects.empty?%>
       <% @projects.each do |project| %>
        <div class="project-box">
          <ul class="inner-project-box">
            <li><span>Project:</span> <%= link_to project.capitalize_stuff, project_path(project), :class => "purple-link" %></li>
            <li><span>Status:</span> <%= project.status %></li>
            <li><span>Due Date:</span> <%= project.format_due_date %></li>
            <li><%= link_to "Edit Project", edit_project_path(project), :class => "purple-link" %></li><br>
          </ul>
        </div>
        <% end %>
      <% end %><br>
    </div>

  <%= link_to "Home", users_path%>    <%= link_to "Logout", "/logout", method: "DELETE"%>

</body>
</html>

app/views/projects/new.html.erb
<%= render partial: "projects_form", locals: {title_text: "Create Project", submit_text: "Create Project"}%>

app/views/projects/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Fredoka+One|Lato:400,700|Montserrat:400,700|Roboto:400,700" rel="stylesheet">
  <title>Project</title>
</head>
<body class="show-project-page">
  <section id="sideMenu">
    <h2>WePlan</h2>
    <nav>
      <a href="/projects"><i class="fas fa-home"></i>Projects</a>
      <a href="/projects/<%= @project.id %>/edit"><i class="fas fa-paperclip"></i></i>Edit Project</a>
      <a href="/projects/<%= @project.id %>/tasks/new"><i class="fas fa-paperclip"></i></i>Create Task</a>
      <a href="/projects/<%= @project.id %>/notes/new"><i class="fas fa-sticky-note"></i>Create Note</a>
      <a href="/projects/<%= @project.id %>/collaborators/new"><i class="fas fa-sticky-note"></i>Add Collaborator</a>
    </nav>
  </section>

  <header>
    <div class="search-area">
      <i class="fas fa-search"></i>
    <input type="text" name="" value="">
    </div>
    <div class="user-area">
      <%= link_to "Logout", "/logout", method: "DELETE"%>
      <a href="/root">Home</a>
    </div>
  </header>

  <div class="user-project">
    <div class="inner-project-box">
      <div class="title">
        <h1><%=@project.capitalize_stuff %></h1>
      </div>
      <div class="description">
        <h2>Description:</h2>
        <p class="description-content"><%= @project.description %></p>
      </div>
      
    </div>
    
    <div class="project-time">
      <li>Status: <%=@project.status%></li>
      <li>Due Date: <%=@project.format_due_date%></li>
      <div class="collaborators">
        <h3>Collaborators:</h3>
        <ul>
          <% @project.collaborators.each do |c| %>
            <% if c.user != current_user%>
              <li>
                <p class="c-user"><%= link_to c.user.capitalize_stuff, project_collaborator_path(@project.id, c.id), :class => "purple-link"%></p> 
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="task-note-wrapper">
    <div class="tasks">
      <h3>Tasks:</h3>
      <ul class="inner-task">
        <% @project.tasks.each do |task|%>
       
          <li><%= task.capitalize_stuff %><a href="<%= edit_project_task_path(@project.id)%>"></i><span>(Edit Task)</span></a></li>
          
          <ul>
          <li>Status: <%= task.status %></li>
          <li>Due Date: <%= task.format_due_date %></li>
          </ul>
        <% end %>
      </ul>
    </div>
    <div class="notes">
      <h3>Notes:</h3>
      <ul>
        <% @project.notes.each do |note| %>
          <li><%= note.content %>" ~ posted by: <%= note.user.capitalize_stuff %>
          <%= link_to "(Edit Note)", edit_project_note_path(@project.id, note.id),:class => "purple-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</body>
</html>